wallpaper {
		monitor = DP-3
		path = /home/B0LD/Pictures/Wallpapers/sailormoon-lavender.jpg
		fit_mode = contain
}

wallpaper {
		monitor = DP-4
		path = /home/B0LD/Pictures/Wallpapers/sailormoon-lavender-UW.jpg
		fit_mode = cover
}
